"use client";
/* eslint-disable @next/next/no-img-element -- Local object URLs let users crop before uploading. */
import { useRef,useState,type PointerEvent,type KeyboardEvent } from "react";
import { centeredCrop,moveCrop,resizeCrop,type CropRect,type CropCorner } from "@/lib/studio/crop-geometry";
const corners:CropCorner[]=["nw","ne","sw","se"];
const labels={nw:"top left",ne:"top right",sw:"bottom left",se:"bottom right"};
export function CropEditor({src,crop,onChange,enabled,disabled=false,onDimensions}:{src:string;crop:CropRect;onChange:(crop:CropRect)=>void;enabled:boolean;disabled?:boolean;onDimensions?:(width:number,height:number)=>void}){
  const stage=useRef<HTMLDivElement>(null);
  const [aspect,setAspect]=useState(1),[ratio,setRatio]=useState(0);
  const gesture=useRef<{pointerId:number;startX:number;startY:number;crop:CropRect;corner?:CropCorner}|null>(null);
  function point(event:PointerEvent){const box=stage.current!.getBoundingClientRect();return{x:(event.clientX-box.left)/box.width,y:(event.clientY-box.top)/box.height};}
  function start(event:PointerEvent<HTMLElement>,corner?:CropCorner){if(disabled||!enabled||event.button!==0||gesture.current)return;event.preventDefault();event.stopPropagation();event.currentTarget.focus();event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);gesture.current={pointerId:event.pointerId,startX:p.x,startY:p.y,crop:{...crop},corner};}
  function move(event:PointerEvent){const g=gesture.current;if(!g||g.pointerId!==event.pointerId)return;const p=point(event);onChange(g.corner?resizeCrop(g.crop,g.corner,(g.corner.includes("w")?g.crop.x:g.crop.x+g.crop.width)+p.x-g.startX,(g.corner.includes("n")?g.crop.y:g.crop.y+g.crop.height)+p.y-g.startY,ratio?ratio/aspect:undefined):moveCrop(g.crop,p.x-g.startX,p.y-g.startY));}
  function key(event:KeyboardEvent,corner?:CropCorner){if(disabled||!enabled||!event.key.startsWith("Arrow"))return;event.preventDefault();event.stopPropagation();const step=event.shiftKey?.025:.005;const dx=event.key==="ArrowLeft"?-step:event.key==="ArrowRight"?step:0,dy=event.key==="ArrowUp"?-step:event.key==="ArrowDown"?step:0;if(corner)onChange(resizeCrop(crop,corner,(corner.includes("w")?crop.x:crop.x+crop.width)+dx,(corner.includes("n")?crop.y:crop.y+crop.height)+dy,ratio?ratio/aspect:undefined));else onChange(moveCrop(crop,dx,dy));}
  return <div>
    {enabled&&<><div className="studio-row" style={{marginBottom:12}}><label className="studio-field" style={{margin:0,flex:1}}>Crop shape<select disabled={disabled} value={ratio} onChange={e=>{const r=Number(e.target.value);setRatio(r);onChange(centeredCrop(aspect,r||undefined));}}><option value={0}>Free shape</option><option value={1}>Square · 1:1</option><option value={3}>Wide logo · 3:1</option><option value={16/9}>Landscape · 16:9</option><option value={4/5}>Portrait · 4:5</option></select></label><button className="studio-button small" disabled={disabled} onClick={()=>{setRatio(0);onChange(centeredCrop(aspect));}}>Reset crop</button></div><p className="studio-muted" id="crop-instructions" style={{fontSize:12,marginBottom:12}}>Drag the selection to move it. Drag a corner to resize. You can also focus the selection or a corner and use arrow keys; hold Shift for larger steps.</p></>}
    <div ref={stage} className="studio-crop-stage" style={{position:"relative",lineHeight:0,overflow:"hidden",background:"#e8ebe5",touchAction:enabled?"none":"auto",userSelect:"none"}}>
      <img src={src} alt="Original artwork" draggable={false} style={{display:"block",width:"100%",height:"auto"}} onLoad={e=>{const image=e.currentTarget;setAspect(image.naturalWidth/image.naturalHeight);onDimensions?.(image.naturalWidth,image.naturalHeight);}}/>
      {enabled&&<div className="studio-crop-selection" role="group" tabIndex={disabled?-1:0} aria-label="Move crop selection" aria-describedby="crop-instructions" onPointerDown={e=>start(e)} onPointerMove={move} onPointerUp={()=>{gesture.current=null;}} onPointerCancel={()=>{gesture.current=null;}} onKeyDown={e=>key(e)} style={{position:"absolute",left:`${crop.x*100}%`,top:`${crop.y*100}%`,width:`${crop.width*100}%`,height:`${crop.height*100}%`,border:"2px solid white",outline:"1px solid #a44832",boxShadow:"0 0 0 9999px #0008",cursor:disabled?"default":"move",touchAction:"none"}}>
        {[1,2].map(n=><span key={n} aria-hidden style={{position:"absolute",inset:0,left:`${n*100/3}%`,width:1,background:"#ffffff65",pointerEvents:"none"}}/>)}
        {[1,2].map(n=><span key={n} aria-hidden style={{position:"absolute",inset:0,top:`${n*100/3}%`,height:1,background:"#ffffff65",pointerEvents:"none"}}/>)}
        {corners.map(c=><button key={c} type="button" disabled={disabled} aria-label={`Resize crop ${labels[c]}`} onPointerDown={e=>start(e,c)} onPointerMove={move} onPointerUp={e=>{e.stopPropagation();gesture.current=null;}} onPointerCancel={()=>{gesture.current=null;}} onKeyDown={e=>key(e,c)} style={{position:"absolute",width:24,height:24,border:"3px solid #a44832",borderRadius:4,background:"white",left:c.includes("w")?0:"auto",right:c.includes("e")?0:"auto",top:c.includes("n")?0:"auto",bottom:c.includes("s")?0:"auto",cursor:`${c}-resize`,touchAction:"none",padding:0}}/>)}
      </div>}
    </div>
    {enabled&&<details style={{marginTop:15}}><summary style={{fontSize:12,cursor:"pointer"}}>Precise crop coordinates</summary><div className="studio-two" style={{marginTop:12}}>{(["x","y","width","height"] as const).map(k=><label className="studio-field" key={k}>{k} (%)<input type="number" step="0.1" min={k==="width"||k==="height"?.5:0} max={100} disabled={disabled} value={Number((crop[k]*100).toFixed(1))} onChange={e=>{const n=Number(e.target.value)/100;if(!Number.isFinite(n))return;const next={...crop,[k]:n};next.width=Math.max(.005,Math.min(1,next.width));next.height=Math.max(.005,Math.min(1,next.height));next.x=Math.max(0,Math.min(1-next.width,next.x));next.y=Math.max(0,Math.min(1-next.height,next.y));setRatio(0);onChange(next);}}/></label>)}</div></details>}
  </div>;
}
