"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { request } from "@/lib/studio/client";
import { sections } from "./EntryManager";
import type { Actor } from "@/lib/studio/access";
import type { Kind } from "@/lib/studio/validation";
export function Dashboard({actor}:{actor:Actor}){const[status,setStatus]=useState<{counts:{kind:Kind;total:number;published:number;review:number}[];workerHealthy:boolean}|null>(null),[error,setError]=useState("");useEffect(()=>{request<typeof status>("/api/studio/status").then(setStatus).catch(e=>setError(e.message));},[]);return <><div className="studio-heading"><div><p className="studio-muted" style={{marginBottom:6}}>Your workspace</p><h1>Welcome, {actor.name.split(" ")[0]}</h1><p className="studio-muted">Everything your team needs to keep NammaOffice up to date.</p></div><Link href="/admin/blogs?new=1" className="studio-button primary">Create a story</Link></div>{error&&<div className="studio-alert" role="alert">{error}</div>}{status&&!status.workerHealthy&&<div className="studio-alert" role="alert">The background worker is not responding. Uploads will stay queued and scheduled content will wait until it restarts.</div>}<div className="studio-grid">{Object.entries(sections).filter(([k])=>actor.role!=="author"||!["logo","testimonial","promotion"].includes(k)).map(([kind,s])=>{const count=status?.counts.find(c=>c.kind===kind);return <Link className="studio-card" href={`/admin/${s.path}`} key={kind}><h2>{s.label}</h2><div className="studio-stat">{count?.total??0}</div><p className="studio-muted">{count?.published??0} published · {count?.review??0} awaiting review</p></Link>;})}</div><div className="studio-two" style={{marginTop:24}}><section className="studio-card"><h2>A clear publishing workflow</h2><p className="studio-muted" style={{marginTop:12}}>Save your work as a draft, preview it, then publish when it is ready. Changes to an existing page stay private until you publish them.</p><div className="studio-row" style={{marginTop:20}}><span className="studio-badge">Draft</span>→<span className="studio-badge review">Review</span>→<span className="studio-badge published">Published</span></div></section><section className="studio-card"><h2>Your media stays reusable</h2><p className="studio-muted" style={{marginTop:12}}>Upload once, keep the original, and use the prepared images across your content. Images in use are protected from deletion.</p><Link href="/admin/media" className="studio-button" style={{marginTop:20}}>Open media library</Link></section></div></>;}
export function Activity(){const[rows,setRows]=useState<{id:string;action:string;actor:string;entity_id:string;created_at:string}[]>([]),[error,setError]=useState("");useEffect(()=>{request<typeof rows>("/api/studio/audit").then(setRows).catch(e=>setError(e.message));},[]);return <><div className="studio-heading"><div><h1>Activity log</h1><p className="studio-muted">The latest 100 changes to content, media and staff access.</p></div></div>{error&&<div className="studio-alert" role="alert">{error}</div>}<div className="studio-card studio-scroll" style={{padding:0}}><table className="studio-table"><thead><tr><th>Action</th><th>By</th><th>Time</th><th>Record</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.action.replaceAll("."," → ")}</td><td>{r.actor||"System"}</td><td>{new Date(r.created_at).toLocaleString()}</td><td style={{fontSize:11}}>{r.entity_id}</td></tr>)}</tbody></table></div></>;}
