"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/studio/client";
export function Login({googleEnabled=false,oauthError=false}:{googleEnabled?:boolean;oauthError?:boolean}){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(oauthError?"Google sign-in could not be completed. Choose the email invited by your administrator, or sign in with your password.":""),[busy,setBusy]=useState(false);const router=useRouter();
 async function submit(event:React.FormEvent){event.preventDefault();setError("");setBusy(true);try{
 const r=await authClient.signIn.email({email,password});if(r.error)throw new Error(r.error.message||"Sign in failed.");router.replace("/admin");router.refresh();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function google(){setError("");setBusy(true);try{const r=await authClient.signIn.social({provider:"google",callbackURL:"/admin",errorCallbackURL:"/admin/login"});if(r.error)throw new Error(r.error.message||"Google sign-in could not be started.");}catch(e){setError((e as Error).message);setBusy(false);}}
 return <div className="studio"><div className="studio-login"><Link href="/" className="studio-brand">nammaoffice.<small>Content studio</small></Link><div className="studio-card" style={{marginTop:28}}><h1>Welcome back</h1><p className="studio-muted" style={{margin:"12px 0 26px"}}>Sign in with your invited staff email. Your email address is your username.</p>{error&&<div className="studio-alert" role="alert">{error}</div>}{googleEnabled&&<><button className="studio-button" style={{width:"100%"}} disabled={busy} onClick={google}><svg aria-hidden width="18" height="18" viewBox="0 0 24 24"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2.1H12v4h5.4a4.6 4.6 0 0 1-2 3v2.5h3.2c1.9-1.7 3-4.2 3-7.4Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.6-2.4l-3.2-2.5c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3.1v2.6A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 14a6 6 0 0 1 0-4V7.4H3.1a10 10 0 0 0 0 9.2L6.4 14Z"/><path fill="#EA4335" d="M12 5.9c1.5 0 2.8.5 3.9 1.5l2.9-2.8A9.5 9.5 0 0 0 12 2a10 10 0 0 0-8.9 5.4L6.4 10C7.2 7.7 9.4 5.9 12 5.9Z"/></svg>Continue with Google</button><p className="studio-muted" style={{textAlign:"center",margin:"20px 0"}}>or use your password</p></>}<form onSubmit={submit}><label className="studio-field">Email address<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="studio-field">Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="studio-button primary" style={{width:"100%"}} disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form><Link href="/admin/forgot-password" style={{display:"block",marginTop:20,fontSize:12,color:"#935039"}}>Forgot your password?</Link></div><p className="studio-muted" style={{fontSize:12,textAlign:"center",marginTop:20}}>Staff access is invitation only.</p></div></div>;
}
export function PasswordReset({token}:{token?:string}){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=token?await authClient.resetPassword({token,newPassword:password}):await authClient.requestPasswordReset({email,redirectTo:"/admin/reset-password"});if(r.error)throw new Error(r.error.message||"Request failed.");setMessage(token?"Your password was updated. You can sign in now.":"If an account exists, a password link has been sent. In local development, an administrator can find it in Team & access → Local mail.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="studio"><div className="studio-login"><div className="studio-card"><h1>{token?"Set your password":"Reset your password"}</h1><p className="studio-muted" style={{margin:"12px 0 24px"}}>Use a unique password with at least 12 characters.</p>{error&&<div role="alert" className="studio-alert">{error}</div>}{message?<div className="studio-alert success" role="status">{message}</div>:<form onSubmit={submit}><label className="studio-field">{token?"New password":"Email address"}<input type={token?"password":"email"} required minLength={token?12:undefined} autoComplete={token?"new-password":"email"} value={token?password:email} onChange={e=>token?setPassword(e.target.value):setEmail(e.target.value)}/></label><button disabled={busy} className="studio-button primary">{busy?"Please wait…":token?"Set password":"Send password link"}</button></form>}<Link href="/admin/login" className="studio-button" style={{marginTop:20}}>Back to sign in</Link></div></div></div>;
}
