"use client";
/* eslint-disable @next/next/no-img-element -- CMS images include authenticated private previews. */
import { useCallback,useEffect,useRef,useState } from "react";
import { Upload,Plus,X,RefreshCw } from "lucide-react";
import type { Media } from "@/lib/studio/media";
import { CropEditor } from "./CropEditor";
import { LogoPreview } from "./LogoPreview";
import type { CropRect } from "@/lib/studio/crop-geometry";
import { request } from "@/lib/studio/client";
export function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(onClose);useEffect(()=>{closeRef.current=onClose;},[onClose]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const first=ref.current?.querySelector<HTMLElement>("button,input,a,select,textarea,[tabindex='0']");first?.focus();const handler=(e:KeyboardEvent)=>{const dialogs=document.querySelectorAll('[role="dialog"]');if(dialogs[dialogs.length-1]!==ref.current)return;if(e.key==="Escape")closeRef.current();if(e.key==="Tab"){const elements=Array.from(ref.current?.querySelectorAll<HTMLElement>("button:not(:disabled),input:not(:disabled),a,select,textarea,[tabindex='0']")||[]).filter(el=>el.getClientRects().length);const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener("keydown",handler);const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",handler);document.body.style.overflow=previousOverflow;previous?.focus();};},[]);
 return <div className="studio studio-overlay"><div className="studio-modal" ref={ref} role="dialog" aria-modal="true" aria-label={title}><div className="studio-heading"><h2>{title}</h2><button className="studio-button small" aria-label="Close dialog" onClick={onClose}><X size={18}/></button></div>{children}</div></div>;
}
function sendFile(form:FormData,onProgress:(progress:number)=>void){return new Promise<Media>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST","/api/studio/media");xhr.timeout=60000;xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText);}catch{reject(new Error("Upload failed. Reload before retrying."));return;}if(xhr.status>=200&&xhr.status<300)resolve(data);else reject(new Error(data.error||"Upload failed."));};xhr.onerror=()=>reject(new Error("Connection lost. Reload the library before retrying."));xhr.ontimeout=()=>reject(new Error("Upload timed out. Reload the library before retrying."));xhr.send(form);});}
export function UploadDialog({purpose,onClose,onReady,initialMedia}:{purpose:"logo"|"image";onClose:()=>void;onReady:(media:Media)=>void;initialMedia?:Media}){
 const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[padding,setPadding]=useState(initialMedia?.options.padding??(purpose==="logo"?8:0)),[trim,setTrim]=useState(initialMedia?.options.trim??false),[cropping,setCropping]=useState(Boolean(initialMedia?.options.crop)),[crop,setCrop]=useState<CropRect>(initialMedia?.options.crop||{x:0,y:0,width:1,height:1}),[dimensions,setDimensions]=useState({width:1,height:1}),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[uploaded,setUploaded]=useState<Media|null>(null),[error,setError]=useState("");
 useEffect(()=>{if(!initialMedia)return;const controller=new AbortController();fetch(`/media/${initialMedia.id}/original`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("The original artwork is unavailable. Reload and try again.");const bytes=await response.blob();if(!controller.signal.aborted)setFile(new File([bytes],initialMedia.filename,{type:initialMedia.mime}));}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[initialMedia]);
 useEffect(()=>{if(!file)return;const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 useEffect(()=>{if(!uploaded||["ready","failed"].includes(uploaded.status))return;let cancelled=false;const poll=setInterval(()=>{request<Media>(`/api/studio/media/${uploaded.id}`).then(m=>{if(!cancelled)setUploaded(m);}).catch(e=>{if(!cancelled)setError(e.message);});},1500);return()=>{cancelled=true;clearInterval(poll);};},[uploaded]);
 async function prepare(){if(!file)return;setError("");setBusy(true);try{const form=new FormData();form.set("file",file);form.set("purpose",purpose);form.set("options",JSON.stringify({padding,trim,...(cropping?{crop}:{})}));setUploaded(await sendFile(form,setProgress));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={purpose==="logo"?"Prepare client artwork":"Upload an image"} onClose={onClose}>
  {error&&<div className="studio-alert" role="alert">{error}</div>}
  {uploaded?<div>
   <div className="studio-image" style={{maxWidth:540,margin:"auto"}}>{uploaded.status==="ready"?<img src={`/media/${uploaded.id}/display`} alt="Processed image preview"/>:<p>{uploaded.status==="failed"?uploaded.error:"Processing your image… You can close this window and find it in the library."}</p>}</div>
   {purpose==="logo"&&uploaded.status==="ready"&&<LogoPreview src={`/media/${uploaded.id}/display`} width={uploaded.variants.display.width} height={uploaded.variants.display.height}/>}
   <div className="studio-row" style={{marginTop:22,justifyContent:"center"}}><button className="studio-button" onClick={()=>{setUploaded(null);setProgress(0);}}>Adjust & prepare again</button><button className="studio-button primary" disabled={uploaded.status!=="ready"} onClick={()=>onReady(uploaded)}>Use this image</button></div>
   <p className="studio-muted" style={{textAlign:"center",marginTop:14}}>The original and previous versions are preserved. A changed crop only goes live after you publish the content.</p>
  </div>:<>
   <div className="studio-two"><div>
    <label className="studio-field">Artwork<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setError("");setCrop({x:0,y:0,width:1,height:1});setCropping(false);}}/><small>{initialMedia&&!file?"Loading the preserved original…":"PNG, JPG, WebP or plain SVG · up to 10 MB · 24 megapixels"}</small></label>
    {file&&<>
     <label className="studio-field"><span className="studio-row"><input type="checkbox" style={{width:"auto",margin:0}} checked={cropping} disabled={busy} onChange={e=>setCropping(e.target.checked)}/>Crop the original</span><small>Move and resize the selection on the artwork.</small></label>
     {purpose==="logo"&&<><label className="studio-field">Padding: {padding}%<input type="range" min={0} max={30} value={padding} disabled={busy} onChange={e=>setPadding(Number(e.target.value))}/></label><label className="studio-field"><span className="studio-row"><input type="checkbox" style={{width:"auto",margin:0}} checked={trim} disabled={busy} onChange={e=>setTrim(e.target.checked)}/>Trim empty border space</span><small>Optional. Check the final prepared preview if trimming is enabled.</small></label></>}
    </>}
    <button className="studio-button primary" disabled={!file||busy} onClick={prepare}><Upload size={16}/>{busy?`Uploading ${progress}%…`:"Prepare image"}</button>
    {purpose==="logo"&&preview&&<LogoPreview src={preview} crop={cropping?crop:undefined} width={dimensions.width} height={dimensions.height} padding={padding}/>}
   </div><div>{preview?<CropEditor key={preview} src={preview} crop={crop} onChange={setCrop} enabled={cropping} disabled={busy} onDimensions={(width,height)=>setDimensions({width,height})}/>:<div className="studio-image"><span className="studio-muted">Your artwork preview</span></div>}</div></div>
   <div className="studio-note" style={{marginTop:24}}>Artwork is fitted without stretching or automatic background removal. Prepare the image to verify the actual saved result, then choose Use this image.</div>
  </>}
 </Modal>;
}
export function AdjustArtwork({id,onReady,onClose}:{id:string;onReady:(media:Media)=>void;onClose:()=>void}){
 const[media,setMedia]=useState<Media|null>(null),[error,setError]=useState("");
 useEffect(()=>{let cancelled=false;request<Media>(`/api/studio/media/${id}`).then(m=>{if(!cancelled)setMedia(m);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[id]);
 return media?<UploadDialog purpose={media.purpose} initialMedia={media} onReady={onReady} onClose={onClose}/>:<Modal title="Load original artwork" onClose={onClose}><p role={error?"alert":"status"}>{error||"Loading original artwork…"}</p></Modal>;
}
export function MediaLibrary({purpose="image",onSelect}:{purpose?:"logo"|"image";onSelect?:(media:Media)=>void}){
 const[items,setItems]=useState<Media[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(""),[trash,setTrash]=useState(false),[upload,setUpload]=useState(false),[adjust,setAdjust]=useState<Media|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{try{const r=await request<{items:Media[];total:number}>(`/api/studio/media?page=${page}&q=${encodeURIComponent(search)}&trash=${trash}`);setItems(r.items);setTotal(r.total);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[page,search,trash]);
 useEffect(()=>{const timeout=setTimeout(load,200);const timer=setInterval(load,5000);return()=>{clearTimeout(timeout);clearInterval(timer);};},[load]);
 async function action(m:Media,a:string){if(a==="trash"&&!confirm("Move this image to trash? Used images cannot be removed."))return;setBusy(m.id);setError("");try{await request(`/api/studio/media/${m.id}`,{method:"PATCH",body:JSON.stringify({action:a,version:m.version})});await load();}catch(e){setError((e as Error).message);}finally{setBusy("");}}
 return <><div className="studio-toolbar"><div className="studio-row"><input className="studio-search" aria-label="Search media" placeholder="Search file names…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{!onSelect&&<button className="studio-button small" onClick={()=>{setTrash(!trash);setPage(1);}}>{trash?"Show library":"View trash"}</button>}</div><button className="studio-button primary" onClick={()=>setUpload(true)}><Plus size={16}/>Upload image</button></div>{error&&<div className="studio-alert" role="alert">{error}</div>}{!items.length?<div className="studio-card studio-empty"><h2>{loading?"Loading media…":trash?"Trash is empty":"Your media library"}</h2><p>{loading?"":"Upload artwork once and reuse it across your content."}</p></div>:<div className="studio-media-grid">{items.map(m=><div className="studio-media-card" key={m.id}><button type="button" className="studio-image" style={{width:"100%"}} disabled={!onSelect||m.status!=="ready"} onClick={()=>onSelect?.(m)} aria-label={`Select ${m.filename}`}>{m.status==="ready"?<img loading="lazy" src={`/media/${m.id}/thumb`} alt={m.filename}/>:<span className={`studio-badge ${m.status}`}>{m.status}</span>}</button><div className="studio-media-caption"><strong>{m.filename}</strong><div className="studio-muted" style={{margin:"5px 0 9px"}}>{(Number(m.bytes)/1024).toFixed(0)} KB · <span className={`studio-badge ${m.status}`}>{m.status}</span></div>{m.error&&<p style={{color:"#a44832"}}>{m.error}</p>}<div className="studio-row">{onSelect?<button className="studio-button small primary" disabled={m.status!=="ready"} onClick={()=>onSelect(m)}>Choose</button>:<>{m.status==="ready"&&<button className="studio-button small" onClick={()=>setAdjust(m)}>Adjust crop</button>}{m.status==="ready"&&<a href={`/media/${m.id}/original`} className="studio-button small">Original</a>}{m.status==="failed"&&<button className="studio-button small" disabled={busy===m.id} onClick={()=>action(m,"retry")}><RefreshCw size={12}/>Retry</button>}<button className="studio-button small" disabled={busy===m.id||["queued","processing"].includes(m.status)} onClick={()=>action(m,trash?"restore":"trash")}>{trash?"Restore":"Trash"}</button></>}</div></div></div>)}</div>}<div className="studio-pagination"><span className="studio-muted">{total} images · page {page}</span><div className="studio-row"><button className="studio-button small" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button className="studio-button small" disabled={page*24>=total} onClick={()=>setPage(page+1)}>Next</button></div></div>{adjust&&<UploadDialog purpose={adjust.purpose} initialMedia={adjust} onClose={()=>setAdjust(null)} onReady={m=>{setAdjust(null);void load();onSelect?.(m);}}/>}{upload&&<UploadDialog purpose={purpose} onClose={()=>{setUpload(false);void load();}} onReady={m=>{setUpload(false);void load();onSelect?.(m);}}/>}</>;
}
export function MediaPicker({purpose,onSelect,onClose}:{purpose:"logo"|"image";onSelect:(m:Media)=>void;onClose:()=>void}){return <Modal title="Choose from your media library" onClose={onClose}><MediaLibrary purpose={purpose} onSelect={onSelect}/></Modal>;}
