import Link from "next/link";
import Image from "next/image";
import { notFound,permanentRedirect } from "next/navigation";
import type { Metadata } from "next";
import { HeroBanner } from "@/components/sections/HeroBanner";
import { VideoEmbed } from "@/components/ui/VideoEmbed";
import { publicEntries,publicEntry,mediaURL,type PublicEntry } from "@/lib/studio/public";
import type { Kind } from "@/lib/studio/validation";
import { RichBody } from "./RichBody";
const paths:Record<string,string>={blog:"blogs",news:"news","case-study":"case-studies"};
const titles:Record<string,string>={blog:"Ideas for better work",news:"News from NammaOffice","case-study":"Client stories"};
export async function ContentIndex({kind,page=1}:{kind:Kind;page?:number}){
 const rows=await publicEntries(kind,13,(page-1)*12),entries=rows.slice(0,12),path=paths[kind];
 return <><HeroBanner eyebrow={kind==="case-study"?"Case studies":kind==="blog"?"The NammaOffice blog":"News & updates"} title={titles[kind]} subtitle={kind==="case-study"?"How teams grow and do their best work at NammaOffice.":"Stories, announcements and useful ideas from our community."}/><section className="content-width py-14 md:py-20">{entries.length?<><div className="grid gap-7 md:grid-cols-2 lg:grid-cols-3">{entries.map(e=><Link href={`/${path}/${e.data.slug}`} key={e.id} className="group overflow-hidden rounded-2xl border border-[var(--color-border)] bg-white"><div className="relative aspect-[16/10] bg-[var(--color-bg)]">{e.data.coverMediaId?<Image src={mediaURL(e.data.coverMediaId)} alt={e.data.coverAlt} fill unoptimized className="object-cover transition-transform duration-500 group-hover:scale-105"/>:<div className="flex h-full items-center justify-center text-[var(--color-navy)] text-4xl font-semibold">N.</div>}</div><div className="p-6"><p className="text-xs uppercase tracking-wider text-[var(--color-gold-deep)]">{e.data.category||kind.replace("-"," ")} · {new Date(e.data.date||e.published_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"})}</p><h2 className="mt-3 text-xl font-semibold text-[var(--color-navy)]">{e.data.title}</h2><p className="mt-3 text-sm leading-7 text-[var(--color-ink-secondary)]">{e.data.excerpt}</p><span className="mt-5 inline-block text-sm font-medium text-[var(--color-gold-deep)]">Read the story →</span></div></Link>)}</div><nav aria-label="Content pages" className="mt-10 flex justify-between">{page>1?<Link href={`/${path}?page=${page-1}`}>← Previous</Link>:<span/>}{rows.length>12&&<Link href={`/${path}?page=${page+1}`}>Next →</Link>}</nav></>:<div className="rounded-2xl border border-[var(--color-border)] p-12 text-center"><h2 className="text-2xl text-[var(--color-navy)]">More stories are on the way</h2><p className="mt-3 text-[var(--color-ink-secondary)]">Visit again for the latest from NammaOffice.</p></div>}</section></>;
}
export async function articleMetadata(kind:Kind,slug:string):Promise<Metadata>{const e=await publicEntry(kind,slug);if(!e)return{};return{title:e.data.seoTitle||e.data.title,description:e.data.seoDescription||e.data.excerpt,alternates:{canonical:`/${paths[kind]}/${e.data.slug}`},openGraph:{type:"article",title:e.data.seoTitle||e.data.title,description:e.data.seoDescription||e.data.excerpt,images:e.data.coverMediaId?[mediaURL(e.data.coverMediaId)]:[]}};}
export function ArticleBody({entry}:{entry:PublicEntry}){const d=entry.data;return <div>{d.coverMediaId&&<div className="relative mb-10 aspect-[16/9] overflow-hidden rounded-2xl"><Image src={mediaURL(d.coverMediaId)} alt={d.coverAlt} fill unoptimized className="object-cover"/></div>}{d.videoUrl&&<div className="mb-10"><VideoEmbed url={d.videoUrl} title={d.title}/></div>}{entry.kind==="case-study"&&<><div className="mb-8 flex flex-wrap gap-5 text-sm text-[var(--color-ink-secondary)]"><span>{d.client}</span><span>{d.industry}</span><span>{d.centre}</span></div>{[{label:"The challenge",value:d.challenge},{label:"The solution",value:d.solution},{label:"The results",value:d.results}].map(s=><section key={s.label} className="mb-9"><h2 className="text-2xl font-semibold text-[var(--color-navy)]">{s.label}</h2><p className="mt-4 whitespace-pre-line text-base leading-8 text-[var(--color-ink-secondary)]">{s.value}</p></section>)}{d.metrics.length>0&&<div className="my-10 grid grid-cols-2 gap-4 md:grid-cols-3">{d.metrics.map((m,i)=><div key={i} className="rounded-xl bg-[var(--color-bg)] p-5"><strong className="text-3xl text-[var(--color-navy)]">{m.value}</strong><p className="mt-2 text-sm">{m.label}</p></div>)}</div>}</>}<RichBody body={d.body}/>{d.gallery.length>0&&<div className="mt-10 grid grid-cols-2 gap-4">{d.gallery.map(id=><a key={id} href={mediaURL(id)} target="_blank" rel="noopener" className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={mediaURL(id)} alt={`${d.title} gallery image`} fill unoptimized className="object-cover"/></a>)}</div>}</div>;}
export async function ContentArticle({kind,slug}:{kind:Kind;slug:string}){const entry=await publicEntry(kind,slug);if(!entry)notFound();if(entry.data.slug!==slug)permanentRedirect(`/${paths[kind]}/${entry.data.slug}`);return <><HeroBanner eyebrow={entry.data.category||titles[kind]} title={entry.data.title} subtitle={entry.data.excerpt}/><article className="content-width py-14 md:py-20"><div className="mx-auto max-w-3xl"><p className="mb-8 text-sm text-[var(--color-ink-secondary)]">{entry.data.authorName&&`${entry.data.authorName} · `}{new Date(entry.data.date||entry.published_at).toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"})}</p><ArticleBody entry={entry}/><Link href={`/${paths[kind]}`} className="mt-12 inline-block text-sm text-[var(--color-gold-deep)]">← All {paths[kind].replace("-"," ")}</Link></div></article></>;}
