import "./env";
import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import sharp from "sharp";
const config=JSON.parse(await fs.readFile(".local/verification.json","utf8"));const base=config.baseURL;
const verificationURL=new URL(config.databaseURL);if(!["127.0.0.1","localhost"].includes(verificationURL.hostname)||!verificationURL.pathname.startsWith("/nammaoffice_verify_"))throw new Error("Tests require an isolated local verification database.");
const db=new Pool({connectionString:config.databaseURL});let checks=0;
function check(value:unknown,message:string){assert(value,message);checks++;}
function eq(actual:unknown,expected:unknown,message:string){assert.equal(actual,expected,message);checks++;}
class Client{jar=new Map<string,string>();async call(path:string,method="GET",body?:unknown,origin=base){const r=await fetch(base+path,{method,headers:{cookie:[...this.jar].map(([k,v])=>`${k}=${v}`).join("; "),origin,...(body instanceof FormData?{}:{"content-type":"application/json"})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),redirect:"manual"});for(const cookie of r.headers.getSetCookie()){const part=cookie.split(";")[0],i=part.indexOf("=");if(/max-age=0/i.test(cookie))this.jar.delete(part.slice(0,i));else this.jar.set(part.slice(0,i),part.slice(i+1));}const text=await r.text();let data;try{data=JSON.parse(text);}catch{data=text;}return{status:r.status,data,headers:r.headers};}async login(role:string){return this.call("/api/auth/sign-in/email","POST",config.users[role]);}}
const admin=new Client(),editor=new Client(),author=new Client(),other=new Client(),anon=new Client();
function body(title:string){return{title,slug:title.toLowerCase().replaceAll(" ","-"),excerpt:"A real workflow verification article.",body:{type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"This is a complete article body."}]}]},date:"2026-09-12"};}
async function save(client:Client,kind:string,data:unknown,id=randomUUID(),version=0){const r=await client.call("/api/studio/entries","POST",{id,kind,version,data});eq(r.status,200,`save ${kind}: ${JSON.stringify(r.data)}`);return r.data;}
async function act(client:Client,e:{id:string;version:number},action:string,extra={}){const r=await client.call(`/api/studio/entries/${e.id}`,"PATCH",{version:e.version,action,...extra});eq(r.status,200,`${action}: ${JSON.stringify(r.data)}`);return r.data;}
async function waitMedia(client:Client,id:string){for(let i=0;i<40;i++){const r=await client.call(`/api/studio/media/${id}`);if(r.data.status==="ready")return r.data;if(r.data.status==="failed")throw new Error(r.data.error);await new Promise(r=>setTimeout(r,500));}throw new Error("Media processing timeout");}
try{
 eq((await anon.call("/api/studio/entries?kind=blog")).status,401,"Anonymous blocked");
 eq((await anon.call("/api/auth/sign-up/email","POST",{email:"public@test.local",password:"never-create-account",name:"Public"})).status,404,"Public registration blocked");
 eq((await anon.call("/api/admin/login","POST",{password:"old-password"})).status,410,"Legacy login retired");
 for(const [name,c] of Object.entries({admin,editor,author,other}))eq((await c.login(name)).status,200,`${name} login`);
 eq((await admin.call("/api/studio/entries?kind=logo")).status,200,"Admin can work immediately after password login");
 eq((await admin.call("/api/auth/two-factor/enable","POST",{password:config.users.admin.password})).status,404,"Retired MFA enrollment endpoint is unavailable");
 eq((await anon.call("/api/auth/two-factor/verify-totp","POST",{code:"123456"})).status,404,"Retired MFA challenge endpoint is unavailable");
 eq((await anon.call("/api/auth/sign-in/social","POST",{provider:"google"})).status,404,"Unconfigured Google sign-in stays unavailable");
 eq((await editor.call("/api/studio/users")).status,403,"Editor cannot manage users");eq((await author.call("/api/studio/entries?kind=logo")).status,403,"Author cannot manage logos");
 const entry=await save(author,"blog",body("Initial blog"));eq((await anon.call("/blogs/initial-blog")).status,404,"Draft stays private");eq((await other.call(`/api/studio/entries/${entry.id}`)).status,403,"Author ownership enforced");
 eq((await author.call(`/api/studio/entries/${entry.id}`,"PATCH",{action:"publish",version:entry.version})).status,403,"Author cannot publish");
 const reviewed=await act(author,entry,"review");let published=await act(editor,reviewed,"publish");eq((await anon.call("/blogs/initial-blog")).status,200,"Published blog visible");
 const edited=await save(author,"blog",{...body("Revised blog"),slug:"renamed-blog"},entry.id,published.version);const old=await anon.call("/blogs/initial-blog");eq(old.status,200,"Published revision retained");check(String(old.data).includes("Initial blog")&&!String(old.data).includes("Revised blog"),"Unpublished title private");eq((await anon.call("/blogs/renamed-blog")).status,404,"New draft URL private");
 const stale=await author.call("/api/studio/entries","POST",{id:entry.id,kind:"blog",version:published.version,data:body("Stale overwrite")});eq(stale.status,409,"Stale editor rejected");
 published=await act(editor,edited,"publish");const redirect=await anon.call("/blogs/initial-blog");eq(redirect.status,308,"Old slug redirects");eq(redirect.headers.get("location"),"/blogs/renamed-blog","Correct redirect target");eq((await anon.call("/blogs/renamed-blog")).status,200,"New published slug visible");
 const duplicate=await editor.call("/api/studio/entries","POST",{id:randomUUID(),kind:"blog",version:0,data:body("Initial blog")});eq(duplicate.status,409,"Historical slug cannot be stolen");
 const revisions=await author.call(`/api/studio/entries/${entry.id}?revisions=1`);check(revisions.data.length>=4,"Revision history retained");const first=revisions.data[revisions.data.length-1];const restored=await act(author,published,"restore-revision",{revisionId:first.id});eq(restored.draft.title,"Initial blog","Revision restored as draft");eq((await anon.call("/blogs/renamed-blog")).status,200,"Restore leaves public revision intact");
 const badDoc=await author.call("/api/studio/entries","POST",{id:randomUUID(),kind:"blog",version:0,data:{...body("Bad html"),body:{type:"doc",content:[{type:"script",text:"alert(1)"}]}}});eq(badDoc.status,422,"Unsafe rich text rejected");
 const csrf=await editor.call("/api/studio/entries","POST",{id:randomUUID(),kind:"news",version:0,data:body("CSRF")},"https://attacker.invalid");eq(csrf.status,403,"Cross-origin mutation blocked");
 const png=await sharp({create:{width:900,height:300,channels:4,background:{r:32,g:100,b:180,alpha:0.8}}}).png().toBuffer();
 const upload=async(client:Client,bytes:Buffer,name:string,type:string,purpose="logo",options={padding:8,trim:false})=>{const f=new FormData();f.set("file",new File([new Uint8Array(bytes)],name,{type}));f.set("purpose",purpose);f.set("options",JSON.stringify(options));return client.call("/api/studio/media","POST",f);};
 const uploaded=await upload(editor,png,"logo.png","image/png");eq(uploaded.status,202,"Image accepted");const media=await waitMedia(editor,uploaded.data.id);check(media.variants.display.width>media.variants.display.height,"Logo aspect ratio preserved");eq((await anon.call(`/media/${media.id}/display`)).status,404,"Unpublished image private");eq((await other.call(`/media/${media.id}/display`)).status,404,"Another author cannot see private media");
 const retry=await upload(editor,png,"retry.png","image/png");eq(retry.data.id,media.id,"Repeated upload deduplicated");
 let logo=await save(editor,"logo",{name:"Verified brand",mediaId:media.id,alt:"Verified brand",order:1});logo=await act(editor,logo,"publish");eq((await anon.call(`/media/${media.id}/display`)).status,200,"Published image visible");eq((await anon.call(`/media/${media.id}/original`)).status,404,"Original remains private");
 eq((await editor.call(`/api/studio/media/${media.id}`,"PATCH",{action:"trash",version:media.version})).status,409,"Referenced image protected");
 const invalid=await upload(editor,Buffer.from("not an image"),"fake.png","image/png");eq(invalid.status,422,"Spoofed image rejected");
 const svg=await upload(editor,Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="50"><script>alert(1)</script><rect width="100" height="50"/></svg>'),"script.svg","image/svg+xml");eq(svg.status,422,"Active SVG rejected");
 const validSvg=await upload(editor,Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="50"><rect width="100" height="50" fill="#285683"/></svg>'),"valid.svg","image/svg+xml");eq(validSvg.status,202,"Plain SVG accepted");await waitMedia(editor,validSvg.data.id);checks++;
 const badCrop=await upload(editor,png,"crop.png","image/png","logo",{padding:8,trim:false,crop:{x:.9,y:0,width:.5,height:1}} as never);eq(badCrop.status,422,"Out-of-bounds crop rejected");
 const replacement=await upload(editor,await sharp(png).tint({r:220,g:80,b:10}).png().toBuffer(),"replacement.png","image/png");const media2=await waitMedia(editor,replacement.data.id);const draftLogo=await save(editor,"logo",{...logo.draft,mediaId:media2.id},logo.id,logo.version);check(String((await anon.call("/")).data).includes(media.id),"Old logo stays visible while replacement is a draft");logo=await act(editor,draftLogo,"publish");check(String((await anon.call("/")).data).includes(media2.id),"Published replacement appears");
 eq((await editor.call(`/api/studio/media/${media.id}`,"PATCH",{action:"trash",version:media.version})).status,409,"Old artwork retained for revision recovery");
 let news=await save(editor,"news",body("Scheduled news"));news=await act(editor,news,"schedule",{scheduledAt:new Date(Date.now()+120000).toISOString()});eq((await anon.call("/news/scheduled-news")).status,404,"Future schedule private");await db.query("UPDATE studio_entries SET scheduled_at=now()-interval '1 second' WHERE id=$1",[news.id]);
 for(let i=0;i<20;i++){if((await anon.call("/news/scheduled-news")).status===200)break;await new Promise(r=>setTimeout(r,500));}eq((await anon.call("/news/scheduled-news")).status,200,"Worker publishes due content");
 const study=await save(editor,"case-study",{...body("A case study"),client:"Verification company",challenge:"Challenge",solution:"Solution",results:"Results",metrics:[{value:"2x",label:"Example metric"}]});await act(editor,study,"publish");eq((await anon.call("/case-studies/a-case-study")).status,200,"Case study published");
 let testimonial=await save(editor,"testimonial",{name:"Verification author",quote:"A test testimonial.",company:"Test company",order:0});testimonial=await act(editor,testimonial,"publish");check(String((await anon.call("/")).data).includes("A test testimonial."),"Testimonial published");await act(editor,testimonial,"archive");check(!String((await anon.call("/")).data).includes("A test testimonial."),"Testimonial archived");
 const trashed=await act(editor,restored,"trash");eq((await anon.call("/blogs/renamed-blog")).status,404,"Trash unpublishes content");const restoredTrash=await act(editor,trashed,"restore-trash");eq(restoredTrash.workflow,"draft","Trash restore is draft");eq((await anon.call("/blogs/renamed-blog")).status,404,"Trash restore does not republish");
 const invite=await admin.call("/api/studio/users","POST",{name:"Invited staff",email:"invited@studio-test.local",role:"author"});eq(invite.status,201,"Staff invitation created");const mail=await admin.call("/api/studio/mail");check(mail.data.some((m:{to:string})=>m.to==="invited@studio-test.local"),"Invitation stored only in local outbox");
 const lastAdmin=await admin.call("/api/studio/users","PATCH",{id:config.users.admin.id,action:"disable"});eq(lastAdmin.status,409,"Last administrator protected");
 eq((await admin.call("/api/studio/users","PATCH",{id:config.users.other.id,action:"disable"})).status,200,"Disable staff account");eq((await other.call("/api/studio/entries?kind=blog")).status,401,"Disabled session revoked");
 await db.query('DELETE FROM "rateLimit"');
 const disabledLogin=await new Client().call("/api/auth/sign-in/email","POST",{email:config.users.other.email,password:config.users.other.password});eq(disabledLogin.status,403,"Disabled account cannot sign in again");
 const invitation=mail.data.find((m:{to:string})=>m.to==="invited@studio-test.local");const callbackURL=new URL(invitation.url);const callback=await anon.call(callbackURL.pathname+callbackURL.search);eq(callback.status,302,"Password email callback redirects to reset form");const token=new URL(callback.headers.get("location")!,base).searchParams.get("token");
 const reset=await anon.call("/api/auth/reset-password","POST",{token,newPassword:"Test-only-password-874231!"});eq(reset.status,200,"Invited staff can set their password");
 eq((await anon.call("/api/auth/reset-password","POST",{token,newPassword:"Test-only-password-874231!"})).status,400,"Password reset token cannot be reused");
 const invited=new Client();eq((await invited.call("/api/auth/sign-in/email","POST",{email:"invited@studio-test.local",password:"Test-only-password-874231!"})).status,200,"Invited account can sign in");
 eq((await invited.call("/api/studio/users")).status,403,"Invited author has no administrator access");
 eq((await author.call("/api/studio/entries?kind=promotion")).status,403,"Authors cannot list hero promotions");
 const promotionData={title:"Verification hero event",coverMediaId:media2.id,coverAlt:"Verification event poster",endsAt:new Date(Date.now()+86400000).toISOString(),priority:10,ctaLabel:"Event details",ctaUrl:base+"/news"};
 eq((await author.call("/api/studio/entries","POST",{id:randomUUID(),kind:"promotion",version:0,data:promotionData})).status,403,"Authors cannot create hero promotions");
 let promotion=await save(editor,"promotion",promotionData);
 check(!String((await anon.call("/")).data).includes(promotionData.title),"Draft poster does not appear in hero");
 const missingEnd=await save(editor,"promotion",{...promotionData,title:"Invalid expiry",endsAt:""});eq((await editor.call(`/api/studio/entries/${missingEnd.id}`,"PATCH",{action:"publish",version:missingEnd.version})).status,422,"Poster expiry is required");
 promotion=await act(editor,promotion,"publish");check(String((await anon.call("/")).data).includes(promotionData.title),"Published eligible poster appears in hero");
 const future=await save(editor,"promotion",{...promotionData,title:"Future hero poster",priority:99,startsAt:new Date(Date.now()+3600000).toISOString()});await act(editor,future,"publish");check(!String((await anon.call("/")).data).includes("Future hero poster"),"Display start excludes future poster");
 let revision=await save(editor,"promotion",{...promotionData,title:"Private changed poster"},promotion.id,promotion.version);check(!String((await anon.call("/")).data).includes("Private changed poster"),"Unpublished hero changes remain private");
 revision=await act(editor,revision,"publish");check(String((await anon.call("/")).data).includes("Private changed poster"),"Hero changes appear after publication");
 const timed=await save(editor,"promotion",{...promotionData,title:"Short priority poster",priority:100,endsAt:new Date(Date.now()+5000).toISOString()});await act(editor,timed,"publish");check(String((await anon.call("/")).data).includes("Short priority poster"),"Highest eligible priority wins");
 await new Promise(resolve=>setTimeout(resolve,5500));const afterExpiry=String((await anon.call("/")).data);check(!afterExpiry.includes("Short priority poster")&&afterExpiry.includes("Private changed poster"),"Expiry returns to next eligible poster without worker publication");
 const expiredSchedule=await editor.call(`/api/studio/entries/${future.id}`,"PATCH",{action:"schedule",version:future.version+1,scheduledAt:new Date(Date.now()+2*86400000).toISOString()});eq(expiredSchedule.status,422,"Cannot schedule after poster expiry");
 await act(editor,revision,"archive");check(!String((await anon.call("/")).data).includes("Private changed poster"),"Archiving removes hero poster");
 const tiny=await upload(editor,await sharp({create:{width:80,height:20,channels:4,background:"#123456"}}).png().toBuffer(),"tiny-logo.png","image/png","logo",{padding:10,trim:false});const tinyReady=await waitMedia(editor,tiny.data.id);eq(tinyReady.variants.display.width,96,"Padding uses actual logo width");eq(tinyReady.variants.display.height,36,"Small artwork is not overwhelmed by padding");
 const split=await sharp({create:{width:400,height:200,channels:3,background:"#0000ff"}}).composite([{input:await sharp({create:{width:200,height:200,channels:3,background:"#ff0000"}}).png().toBuffer(),left:200,top:0}]).png().toBuffer();
 const cropped=await upload(editor,split,"crop-pixels.png","image/png","logo",{padding:0,trim:false,crop:{x:.5,y:0,width:.5,height:1}} as never);const cropReady=await waitMedia(editor,cropped.data.id);const prepared=await fetch(base+`/media/${cropReady.id}/display`,{headers:{cookie:[...editor.jar].map(([k,v])=>`${k}=${v}`).join("; ")}});const stats=await sharp(Buffer.from(await prepared.arrayBuffer())).stats();check(stats.channels[0].mean>240&&stats.channels[2].mean<15,"Crop saves the selected pixels from the original");
 const audit=await admin.call("/api/studio/audit");check(audit.data.some((r:{action:string})=>r.action==="entry.publish"),"Publishing audit recorded");check(audit.data.some((r:{action:string})=>r.action==="user.disable"),"User access audit recorded");
 const sitemap=await anon.call("/sitemap.xml");check(String(sitemap.data).includes("/news/scheduled-news")&&!String(sitemap.data).includes("/blogs/renamed-blog"),"Sitemap includes only published content");
 await fs.writeFile(".local/http-verification.json",JSON.stringify({checks,passed:true,at:new Date().toISOString()},null,2));console.log(`PASS: ${checks} CMS production-mode HTTP checks.`);
}finally{await db.end();}
